ame: SonarCloud Monorepo Analysis

on:
  push:
    branches:
      
main
pull_request:
  types: [ opened, synchronize, reopened ]

jobs:
  analyze: # (Mantuve el nombre de tu job original)
    name: Analyze entire repository
    runs-on: ubuntu-latest
    steps:
      
uses: actions/checkout@v4
      with:
        fetch-depth: 0
name: Set up JDK 17
    uses: actions/setup-java@v4
    with:
      java-version: 17
      distribution: 'zulu'
name: Cache Sonar packages
  uses: actions/cache@v4
  with:
    path: ~/.sonar/cache
    key: ${{ runner.os }}-sonar
    restore-keys: ${{ runner.os }}-sonar
name: Cache Maven packages
uses: actions/cache@v4
with:
  path: ~/.m2
  key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
  restore-keys: ${{ runner.os }}-m2

      # --- ESTE ES EL PASO QUE TE FALTABA ---
      
name: Build, test coverage and analyze
      env:# Token para que Sonar pueda comentar en Pull Requests
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}# Token de SonarCloud que configuraste en los Secrets
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar